[package]
name = "coopco"
version = "0.1.0"
authors = ["Daniel Lockyer <thisisdaniellockyer@gmail.com>"]

[dependencies]
rand = "0.3.16"
assert_approx_eq = "1.0"
flot = { git="https://github.com/stevedonovan/flot-rs.git" }

[profile.release]
debug = true
