[package]
name = "coopco"
version = "0.1.0"
authors = ["Daniel Lockyer <thisisdaniellockyer@gmail.com>"]

[dependencies]
rand = "0.4"
assert_approx_eq = "1.0"
bit-vec = { git="https://github.com/neosilky/bit-vec.git" }

[profile.release]
debug = true
